"""empty message

Revision ID: 405c7cb257cd
Revises: 860d114f3d1e
Create Date: 2021-06-20 13:50:26.489483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '405c7cb257cd'
down_revision = '860d114f3d1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))

    op.execute('UPDATE todos SET completed = FALSE WHERE completed is NULL')

    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
